### ISSUE TITLE
Error when installing CLI

### ISSUE THREAD

**Issue by aboutaaron** [datadesk/census-data-downloader#28]
Hi all,

Excited to use this tool! I noticed this error when I just tried installing census-data-downloader:

```
Traceback (most recent call last):
  File "/Users/williamsa/.local/share/virtualenvs/fema-X3N8u1-d/bin/censusdatadownloader", line 6, in <module>
    from census_data_downloader.cli import cmd
  File "/Users/williamsa/.local/share/virtualenvs/fema-X3N8u1-d/lib/python3.7/site-packages/census_data_downloader/__init__.py", line 5, in <module>
    from .tables import TABLE_LIST
ModuleNotFoundError: No module named 'census_data_downloader.tables'
```

I tried installing via `pipx` and `pipenv` and received the same error.

**Comment by palewire** [comment]
Hmm. Will investigate.

**Comment by palewire** [comment]
Something has gone wrong in how PyPI has packaged up the subfolders in the distro. Can fix.

**Comment by palewire** [comment]
I think I got it. Install v0.0.13. Just need to correct some bugs in my setup.py file.
